#ifndef __JOLT_GUI_SYMBOLS_H__
#define __JOLT_GUI_SYMBOLS_H__

#define JOLT_GUI_SYMBOL_BATTERY_EMPTY "\xEF\x80\x80"
#define JOLT_GUI_SYMBOL_BATTERY_1 "\xEF\x80\x81"
#define JOLT_GUI_SYMBOL_BATTERY_2 "\xEF\x80\x82"
#define JOLT_GUI_SYMBOL_BATTERY_3 "\xEF\x80\x83"
#define JOLT_GUI_SYMBOL_BATTERY_CHARGING "\xEF\x80\x84"
#define JOLT_GUI_SYMBOL_BATTERY_DISCONNECT "\xEF\x80\x85"

#define JOLT_GUI_SYMBOL_BLUETOOTH "\xEF\x80\x86"

#define JOLT_GUI_SYMBOL_WIFI_1 "\xEF\x80\x87"
#define JOLT_GUI_SYMBOL_WIFI_2 "\xEF\x80\x88"
#define JOLT_GUI_SYMBOL_WIFI_3 "\xEF\x80\x89"

#define JOLT_GUI_SYMBOL_LOCK "\xEF\x80\x8A"

#endif
