/**
 * @file jolt_gui_symbols.h
 * @brief Unicode macros for custom Jolt symbols
 * @author Brian Pugh
 */

#ifndef __JOLT_GUI_SYMBOLS_H__
#define __JOLT_GUI_SYMBOLS_H__

#if 0
#define JOLT_GUI_SYMBOL_BATTERY_EMPTY "\xEF\x80\x80"
#define JOLT_GUI_SYMBOL_BATTERY_1 "\xEF\x80\x81"
#define JOLT_GUI_SYMBOL_BATTERY_2 "\xEF\x80\x82"
#define JOLT_GUI_SYMBOL_BATTERY_3 "\xEF\x80\x83"
#define JOLT_GUI_SYMBOL_BATTERY_CHARGING "\xEF\x80\x84"
#define JOLT_GUI_SYMBOL_BATTERY_DISCONNECT "\xEF\x80\x85"

#define JOLT_GUI_SYMBOL_BLUETOOTH "\xEF\x80\x86"
#define JOLT_GUI_SYMBOL_BLUETOOTH_CONN "\xEF\x80\x87"

#define JOLT_GUI_SYMBOL_WIFI_1 "\xEF\x80\x88"
#define JOLT_GUI_SYMBOL_WIFI_2 "\xEF\x80\x89"
#define JOLT_GUI_SYMBOL_WIFI_3 "\xEF\x80\x8A"
#define JOLT_GUI_SYMBOL_WIFI_DISCONN "\xEF\x80\x8B"

#define JOLT_GUI_SYMBOL_LOCK "\xEF\x80\x8C"

#define JOLT_GUI_SYMBOL_CHIP "\xEF\x80\x8D"

#else
#define LV_SYMBOL_BATTERY_FULL    "\xef\x89\x80"
#define LV_SYMBOL_BATTERY_3       "\xef\x89\x81"
#define LV_SYMBOL_BATTERY_2       "\xef\x89\x82"
#define LV_SYMBOL_BATTERY_1       "\xef\x89\x83"
#define LV_SYMBOL_BATTERY_EMPTY   "\xef\x89\x84"
#define LV_SYMBOL_BLUETOOTH       "\xef\x8a\x93"


#define JOLT_GUI_SYMBOL_BATTERY_EMPTY LV_SYMBOL_BATTERY_EMPTY
#define JOLT_GUI_SYMBOL_BATTERY_1 LV_SYMBOL_BATTERY_1
#define JOLT_GUI_SYMBOL_BATTERY_2 LV_SYMBOL_BATTERY_2
#define JOLT_GUI_SYMBOL_BATTERY_3 LV_SYMBOL_BATTERY_3
#define JOLT_GUI_SYMBOL_BATTERY_CHARGING LV_SYMBOL_BATTERY_FULL
#define JOLT_GUI_SYMBOL_BATTERY_DISCONNECT LV_SYMBOL_BATTERY_EMPTY

#define JOLT_GUI_SYMBOL_BLUETOOTH LV_SYMBOL_BLUETOOTH
#define JOLT_GUI_SYMBOL_BLUETOOTH_CONN LV_SYMBOL_BLUETOOTH

#define JOLT_GUI_SYMBOL_WIFI_1 LV_SYMBOL_WIFI
#define JOLT_GUI_SYMBOL_WIFI_2 LV_SYMBOL_WIFI
#define JOLT_GUI_SYMBOL_WIFI_3 LV_SYMBOL_WIFI
#define JOLT_GUI_SYMBOL_WIFI_DISCONN LV_SYMBOL_WIFI

#define JOLT_GUI_SYMBOL_LOCK LV_SYMBOL_PAUSE

#define JOLT_GUI_SYMBOL_CHIP LV_SYMBOL_STOP

#endif


#endif
